### ISSUE TITLE
paperclip warnings

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#596]
```
/var/squish/app/squish1/webapps/ROOT/WEB-INF/gems/gems/paperclip-4.3.6/lib/paperclip/storage/filesystem.rb:49: warning: `&' after local variable or literal is interpreted as binary operator
/var/squish/app/squish1/webapps/ROOT/WEB-INF/gems/gems/paperclip-4.3.6/lib/paperclip/storage/filesystem.rb:49: warning: even though it seems like argument prefix
```

**Comment by k41n** [comment]
This warning appear because in paperclip source there is line - 
"resolved_chmod = (@options[:override_file_permissions] &~ 0111) || (0666 &~ File.umask)".
If replace it on 
"resolved_chmod = (@options[:override_file_permissions] & ~0111) || (0666 & ~File.umask)".
warning should be fixed. But it will work similiar as it was before. It's just fix warning. 
I think now it works normal without changes and we can just ignore this warning.

**Comment by ari** [comment]
OK, we'll close this. In the longer term we need to think about unhooking imagemagick so we'll need to upgrade paperclip or move to something else.

**Comment by knightq** [comment]
So, in the end, can we just ignore this warning?

**Comment by ari** [comment]
Yes, just warning in a library we use.
