### ISSUE TITLE
Initialise new tenant properly

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#642]
When I visit `http://.../companies/1/edit` (via the drop-down menu in the right top corner) after a fresh installation of jobsworth 5.0M3 and click there (without changing anything) to the `Save` button, I just get the error message:

> Unable to find internal customer. 

Why? This feels like a bug to me. If it isn't a bug, the error message should IMHO outline to the user/administrator what else should be done or so (to be at least a bit more user friendly).

**Comment by robert-scheck** [comment]
Creating a new customer via `http://…/customers/new` named "Default Company" seems to work around this, but if this is really the right way, the error message should be reworked and outline what the user/admin shall do. Note that the drop-down menu is labelled wrong, related to #496

**Comment by ari** [comment]
This looks like an error when initialising a new database from scratch.

@k41n You should not be able to create a new 'customer' from /customers/new since that should be an action reserved for some sort of API or script. Please ensure it is locked out from the routing rules and has a clear comment about why this is important. We need a test around this as well.

Also, when initialising a new database, a default tenant 1 should be created. I think we need to consolidate all the tenant initialisation code (such as creating default properties, an initial project and milestone, first login user, etc)

**Comment by ari** [comment]
@robert-scheck A beta has been released with new tenants created properly. Please let us know if that works for you.

**Comment by robert-scheck** [comment]
In 5.0 beta 1, this works as expected – thank you.

**Comment by ari** [comment]
Excellent, thanks for letting us know.
