### ISSUE TITLE
Dynamic Render Path Warning in app/views/projects/index.html.erb

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#652]
[Security issue from Hakiri](https://hakiri.io/projects/39ef0784a0fbfc/stacks/02710ff0721fd1/builds/5d356bc8afdb5f/warnings/e17dde832ef6fa): Render path contains parameter value in app/views/projects/index.html.erb

**Comment by k41n** [comment]
I'm not sure that this issue is real. because render path contains only params[:page]. But there is another issue, we don't have pagination on view, users can't go to next page. So users can see only first 100 projects. I think we need to remove pagination parameters from controller and show all projects, or add pagination on view. @ari
