### ISSUE TITLE
Docker install?

### ISSUE THREAD

**Issue by planetahuevo** [ari/jobsworth#678]
Hi, 
I keep coming back to this project and the thing that prevents me to use it and recommend it is always the same: It is too difficult to setup.

Have you considered to create a Docker setup that simplify this?

Thanks

**Comment by ari** [comment]
I don't use docker, so its not something I have experience with. But you might like to do one.

**Comment by planetahuevo** [comment]
I have no idea how to do that. 
Ari, you always answer like that (I have been following the project since it was a clockingit thing).
From my point of view, instead of embrace the other types of support that people can offer, you just shut the door on them with answers like that. 
I might have others ways to help, like suggesting new ideas, but then, I do not want to do that now.

Maybe you could think why, being such a great open source project, not so many people have joined to help with the development... 

Good luck.

**Comment by ari** [comment]
Making requests is easy but writing code is hard. So I could spend a day of my life learning how to use docker and building something for you, but it would give me personally no benefit and I don't have the time.

This isn't one of those open source projects where I'm trying to leverage a community into my commercial paid product. This is open source because I think the code might be useful to others and I want to share my work. If people want to contribute then great.

**Comment by planetahuevo** [comment]
I am not saying that you must build it. 

You are saying everything here and you are not even trying to understand me. 
Contribute is not only code, that is the only thing I am saying here.
